### ISSUE TITLE
Employer model

### ISSUE THREAD

**Issue by 0xazure** [WorkingScholar/workingscholar#13]
Implement Employer model.  Follows similar ideas to #12.
- Model attributes:
  - [x] name
  - [x] username (unique, case-insensitive)
- Associations:
  - [x] `belongs_to` account
- Actions (views & controller):
  - [x] edit
  - [x] index
  - [x] show (employer profile)

**Comment by sheret** [comment]
remove email from model list

**Comment by sheret** [comment]
remove email from employer model list
