### ISSUE TITLE
Match Model

### ISSUE THREAD

**Issue by sheret** [WorkingScholar/workingscholar#56]
Which students/employers have matched

**Comment by sheret** [comment]
@0xazure match button should be on applicant view to send email to corresponding student to indicate a match

**Comment by 0xazure** [comment]
We probably don't actually need a separate model for this.  The Application model should handle most of this for us, we can just add a new column to the table called `matched` or `accepted` or `hired` or something along those lines that indicates a match between an Employer's Posting and an Applicant.
